services:
  postgres:
    image: postgres:16
    container_name: postgres-mcv-demo
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      timeout: 2s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
